const countries = [
  { name: "Afghanistan", ar: "أفغانستان", code: "+93", iso: "af", flag: "🇦🇫" },
  { name: "Albania", ar: "ألبانيا", code: "+355", iso: "al", flag: "🇦🇱" },
  { name: "Algeria", ar: "الجزائر", code: "+213", iso: "dz", flag: "🇩🇿" },
  { name: "Andorra", ar: "أندورا", code: "+376", iso: "ad", flag: "🇦🇩" },
  { name: "Angola", ar: "أنغولا", code: "+244", iso: "ao", flag: "🇦🇴" },
  { name: "Antigua and Barbuda", ar: "أنتيغوا وبربودا", code: "+1268", iso: "ag", flag: "🇦🇬" },
  { name: "Argentina", ar: "الأرجنتين", code: "+54", iso: "ar", flag: "🇦🇷" },
  { name: "Armenia", ar: "أرمينيا", code: "+374", iso: "am", flag: "🇦🇲" },
  { name: "Australia", ar: "أستراليا", code: "+61", iso: "au", flag: "🇦🇺" },
  { name: "Austria", ar: "النمسا", code: "+43", iso: "at", flag: "🇦🇹" },
  { name: "Azerbaijan", ar: "أذربيجان", code: "+994", iso: "az", flag: "🇦🇿" },
  { name: "Bahamas", ar: "جزر البهاما", code: "+1242", iso: "bs", flag: "🇧🇸" },
  { name: "Bahrain", ar: "البحرين", code: "+973", iso: "bh", flag: "🇧🇭" },
  { name: "Bangladesh", ar: "بنغلاديش", code: "+880", iso: "bd", flag: "🇧🇩" },
  { name: "Barbados", ar: "بربادوس", code: "+1246", iso: "bb", flag: "🇧🇧" },
  { name: "Belarus", ar: "بيلاروس", code: "+375", iso: "by", flag: "🇧🇾" },
  { name: "Belgium", ar: "بلجيكا", code: "+32", iso: "be", flag: "🇧🇪" },
  { name: "Belize", ar: "بليز", code: "+501", iso: "bz", flag: "🇧🇿" },
  { name: "Benin", ar: "بنين", code: "+229", iso: "bj", flag: "🇧🇯" },
  { name: "Bhutan", ar: "بوتان", code: "+975", iso: "bt", flag: "🇧🇹" },
  { name: "Bolivia", ar: "بوليفيا", code: "+591", iso: "bo", flag: "🇧🇴" },
  { name: "Bosnia and Herzegovina", ar: "البوسنة والهرسك", code: "+387", iso: "ba", flag: "🇧🇦" },
  { name: "Botswana", ar: "بوتسوانا", code: "+267", iso: "bw", flag: "🇧🇼" },
  { name: "Brazil", ar: "البرازيل", code: "+55", iso: "br", flag: "🇧🇷" },
  { name: "Brunei", ar: "بروناي", code: "+673", iso: "bn", flag: "🇧🇳" },
  { name: "Bulgaria", ar: "بلغاريا", code: "+359", iso: "bg", flag: "🇧🇬" },
  { name: "Burkina Faso", ar: "بوركينا فاسو", code: "+226", iso: "bf", flag: "🇧🇫" },
  { name: "Burundi", ar: "بوروندي", code: "+257", iso: "bi", flag: "🇧🇮" },
  { name: "Cabo Verde", ar: "الرأس الأخضر", code: "+238", iso: "cv", flag: "🇨🇻" },
  { name: "Cambodia", ar: "كمبوديا", code: "+855", iso: "kh", flag: "🇰🇭" },
  { name: "Cameroon", ar: "الكاميرون", code: "+237", iso: "cm", flag: "🇨🇲" },
  { name: "Canada", ar: "كندا", code: "+1", iso: "ca", flag: "🇨🇦" },
  { name: "Central African Republic", ar: "جمهورية أفريقيا الوسطى", code: "+236", iso: "cf", flag: "🇨🇫" },
  { name: "Chad", ar: "تشاد", code: "+235", iso: "td", flag: "🇹🇩" },
  { name: "Chile", ar: "تشيلي", code: "+56", iso: "cl", flag: "🇨🇱" },
  { name: "China", ar: "الصين", code: "+86", iso: "cn", flag: "🇨🇳" },
  { name: "Colombia", ar: "كولومبيا", code: "+57", iso: "co", flag: "🇨🇴" },
  { name: "Comoros", ar: "جزر القمر", code: "+269", iso: "km", flag: "🇰🇲" },
  { name: "Congo (Republic of the Congo)", ar: "الكونغو - برازافيل", code: "+242", iso: "cg", flag: "🇨🇬" },
  { name: "Congo (Democratic Republic of the Congo)", ar: "الكونغو - كينشاسا", code: "+243", iso: "cd", flag: "🇨🇩" },
  { name: "Costa Rica", ar: "كوستاريكا", code: "+506", iso: "cr", flag: "🇨🇷" },
  { name: "Croatia", ar: "كرواتيا", code: "+385", iso: "hr", flag: "🇭🇷" },
  { name: "Cuba", ar: "كوبا", code: "+53", iso: "cu", flag: "🇨🇺" },
  { name: "Cyprus", ar: "قبرص", code: "+357", iso: "cy", flag: "🇨🇾" },
  { name: "Czechia", ar: "التشيك", code: "+420", iso: "cz", flag: "🇨🇿" },
  { name: "Denmark", ar: "الدانمرك", code: "+45", iso: "dk", flag: "🇩🇰" },
  { name: "Djibouti", ar: "جيبوتي", code: "+253", iso: "dj", flag: "🇩🇯" },
  { name: "Dominica", ar: "دومينيكا", code: "+1767", iso: "dm", flag: "🇩🇲" },
  { name: "Dominican Republic", ar: "جمهورية الدومينيكان", code: "+1849", iso: "do", flag: "🇩🇴" },
  { name: "Ecuador", ar: "الإكوادور", code: "+593", iso: "ec", flag: "🇪🇨" },
  { name: "Egypt", ar: "مصر", code: "+20", iso: "eg", flag: "🇪🇬" },
  { name: "El Salvador", ar: "السلفادور", code: "+503", iso: "sv", flag: "🇸🇻" },
  { name: "Equatorial Guinea", ar: "غينيا الاستوائية", code: "+240", iso: "gq", flag: "🇬🇶" },
  { name: "Eritrea", ar: "إريتريا", code: "+291", iso: "er", flag: "🇪🇷" },
  { name: "Estonia", ar: "إستونيا", code: "+372", iso: "ee", flag: "🇪🇪" },
  { name: "Eswatini", ar: "إسواتيني", code: "+268", iso: "sz", flag: "🇸🇿" },
  { name: "Ethiopia", ar: "إثيوبيا", code: "+251", iso: "et", flag: "🇪🇹" },
  { name: "Fiji", ar: "فيجي", code: "+679", iso: "fj", flag: "🇫🇯" },
  { name: "Finland", ar: "فنلندا", code: "+358", iso: "fi", flag: "🇫🇮" },
  { name: "France", ar: "فرنسا", code: "+33", iso: "fr", flag: "🇫🇷" },
  { name: "Gabon", ar: "الغابون", code: "+241", iso: "ga", flag: "🇬🇦" },
  { name: "Gambia", ar: "غامبيا", code: "+220", iso: "gm", flag: "🇬🇲" },
  { name: "Georgia", ar: "جورجيا", code: "+995", iso: "ge", flag: "🇬🇪" },
  { name: "Germany", ar: "ألمانيا", code: "+49", iso: "de", flag: "🇩🇪" },
  { name: "Ghana", ar: "غانا", code: "+233", iso: "gh", flag: "🇬🇭" },
  { name: "Greece", ar: "اليونان", code: "+30", iso: "gr", flag: "🇬🇷" },
  { name: "Grenada", ar: "غرينادا", code: "+1473", iso: "gd", flag: "🇬🇩" },
  { name: "Guatemala", ar: "غواتيمالا", code: "+502", iso: "gt", flag: "🇬🇹" },
  { name: "Guinea", ar: "غينيا", code: "+224", iso: "gn", flag: "🇬🇳" },
  { name: "Guinea-Bissau", ar: "غينيا بيساو", code: "+245", iso: "gw", flag: "🇬🇼" },
  { name: "Guyana", ar: "غيانا", code: "+592", iso: "gy", flag: "🇬🇾" },
  { name: "Haiti", ar: "هايتي", code: "+509", iso: "ht", flag: "🇭🇹" },
  { name: "Honduras", ar: "هندوراس", code: "+504", iso: "hn", flag: "🇭🇳" },
  { name: "Hungary", ar: "هنغاريا", code: "+36", iso: "hu", flag: "🇭🇺" },
  { name: "Iceland", ar: "آيسلندا", code: "+354", iso: "is", flag: "🇮🇸" },
  { name: "India", ar: "الهند", code: "+91", iso: "in", flag: "🇮🇳" },
  { name: "Indonesia", ar: "إندونيسيا", code: "+62", iso: "id", flag: "🇮🇩" },
  { name: "Iran", ar: "إيران", code: "+98", iso: "ir", flag: "🇮🇷" },
  { name: "Iraq", ar: "العراق", code: "+964", iso: "iq", flag: "🇮🇶" },
  { name: "Ireland", ar: "أيرلندا", code: "+353", iso: "ie", flag: "🇮🇪" },
  { name: "Israel", ar: "إسرائيل", code: "+972", iso: "il", flag: "🇮🇱" },
  { name: "Italy", ar: "إيطاليا", code: "+39", iso: "it", flag: "🇮🇹" },
  { name: "Jamaica", ar: "جامايكا", code: "+1876", iso: "jm", flag: "🇯🇲" },
  { name: "Japan", ar: "اليابان", code: "+81", iso: "jp", flag: "🇯🇵" },
  { name: "Jordan", ar: "الأردن", code: "+962", iso: "jo", flag: "🇯🇴" },
  { name: "Kazakhstan", ar: "كازاخستان", code: "+7", iso: "kz", flag: "🇰🇿" },
  { name: "Kenya", ar: "كينيا", code: "+254", iso: "ke", flag: "🇰🇪" },
  { name: "Kiribati", ar: "كيريباتي", code: "+686", iso: "ki", flag: "🇰🇮" },
  { name: "Kuwait", ar: "الكويت", code: "+965", iso: "kw", flag: "🇰🇼" },
  { name: "Kyrgyzstan", ar: "قيرغيزستان", code: "+996", iso: "kg", flag: "🇰🇬" },
  { name: "Laos", ar: "لاوس", code: "+856", iso: "la", flag: "🇱🇦" },
  { name: "Latvia", ar: "لاتفيا", code: "+371", iso: "lv", flag: "🇱🇻" },
  { name: "Lebanon", ar: "لبنان", code: "+961", iso: "lb", flag: "🇱🇧" },
  { name: "Lesotho", ar: "ليسوتو", code: "+266", iso: "ls", flag: "🇱🇸" },
  { name: "Liberia", ar: "ليبيريا", code: "+231", iso: "lr", flag: "🇱🇷" },
  { name: "Libya", ar: "ليبيا", code: "+218", iso: "ly", flag: "🇱🇾" },
  { name: "Liechtenstein", ar: "ليختنشتاين", code: "+423", iso: "li", flag: "🇱🇮" },
  { name: "Lithuania", ar: "ليتوانيا", code: "+370", iso: "lt", flag: "🇱🇹" },
  { name: "Luxembourg", ar: "لوكسمبورغ", code: "+352", iso: "lu", flag: "🇱🇺" },
  { name: "Madagascar", ar: "مدغشقر", code: "+261", iso: "mg", flag: "🇲🇬" },
  { name: "Malawi", ar: "ملاوي", code: "+265", iso: "mw", flag: "🇲🇼" },
  { name: "Malaysia", ar: "ماليزيا", code: "+60", iso: "my", flag: "🇲🇾" },
  { name: "Maldives", ar: "جزر المالديف", code: "+960", iso: "mv", flag: "🇲🇻" },
  { name: "Mali", ar: "مالي", code: "+223", iso: "ml", flag: "🇲🇱" },
  { name: "Malta", ar: "مالطا", code: "+356", iso: "mt", flag: "🇲🇹" },
  { name: "Marshall Islands", ar: "جزر مارشال", code: "+692", iso: "mh", flag: "🇲🇭" },
  { name: "Mauritania", ar: "موريتانيا", code: "+222", iso: "mr", flag: "🇲🇷" },
  { name: "Mauritius", ar: "موريشيوس", code: "+230", iso: "mu", flag: "🇲🇺" },
  { name: "Mexico", ar: "المكسيك", code: "+52", iso: "mx", flag: "🇲🇽" },
  { name: "Micronesia", ar: "ميكرونيزيا", code: "+691", iso: "fm", flag: "🇫🇲" },
  { name: "Moldova", ar: "مولدوفا", code: "+373", iso: "md", flag: "🇲🇩" },
  { name: "Monaco", ar: "موناكو", code: "+377", iso: "mc", flag: "🇲🇨" },
  { name: "Mongolia", ar: "منغوليا", code: "+976", iso: "mn", flag: "🇲🇳" },
  { name: "Montenegro", ar: "الجبل الأسود", code: "+382", iso: "me", flag: "🇲🇪" },
  { name: "Morocco", ar: "المغرب", code: "+212", iso: "ma", flag: "🇲🇦" },
  { name: "Mozambique", ar: "موزمبيق", code: "+258", iso: "mz", flag: "🇲🇿" },
  { name: "Myanmar", ar: "ميانمار (بورما)", code: "+95", iso: "mm", flag: "🇲🇲" },
  { name: "Namibia", ar: "ناميبيا", code: "+264", iso: "na", flag: "🇳🇦" },
  { name: "Nauru", ar: "ناورو", code: "+674", iso: "nr", flag: "🇳🇷" },
  { name: "Nepal", ar: "نيبال", code: "+977", iso: "np", flag: "🇳🇵" },
  { name: "Netherlands", ar: "هولندا", code: "+31", iso: "nl", flag: "🇳🇱" },
  { name: "New Zealand", ar: "نيوزيلندا", code: "+64", iso: "nz", flag: "🇳🇿" },
  { name: "Nicaragua", ar: "نيكاراغوا", code: "+505", iso: "ni", flag: "🇳🇮" },
  { name: "Niger", ar: "النيجر", code: "+227", iso: "ne", flag: "🇳🇪" },
  { name: "Nigeria", ar: "نيجيريا", code: "+234", iso: "ng", flag: "🇳🇬" },
  { name: "North Korea", ar: "كوريا الشمالية", code: "+850", iso: "kp", flag: "🇰🇵" },
  { name: "North Macedonia", ar: "مقدونيا الشمالية", code: "+389", iso: "mk", flag: "🇲🇰" },
  { name: "Norway", ar: "النرويج", code: "+47", iso: "no", flag: "🇳🇴" },
  { name: "Oman", ar: "عُمان", code: "+968", iso: "om", flag: "🇴🇲" },
  { name: "Pakistan", ar: "باكستان", code: "+92", iso: "pk", flag: "🇵🇰" },
  { name: "Palau", ar: "بالاو", code: "+680", iso: "pw", flag: "🇵🇼" },
  { name: "Palestine", ar: "الأراضي الفلسطينية", code: "+970", iso: "ps", flag: "🇵🇸" },
  { name: "Panama", ar: "بنما", code: "+507", iso: "pa", flag: "🇵🇦" },
  { name: "Papua New Guinea", ar: "بابوا غينيا الجديدة", code: "+675", iso: "pg", flag: "🇵🇬" },
  { name: "Paraguay", ar: "باراغواي", code: "+595", iso: "py", flag: "🇵🇾" },
  { name: "Peru", ar: "بيرو", code: "+51", iso: "pe", flag: "🇵🇪" },
  { name: "Philippines", ar: "الفلبين", code: "+63", iso: "ph", flag: "🇵🇭" },
  { name: "Poland", ar: "بولندا", code: "+48", iso: "pl", flag: "🇵🇱" },
  { name: "Portugal", ar: "البرتغال", code: "+351", iso: "pt", flag: "🇵🇹" },
  { name: "Qatar", ar: "قطر", code: "+974", iso: "qa", flag: "🇶🇦" },
  { name: "Romania", ar: "رومانيا", code: "+40", iso: "ro", flag: "🇷🇴" },
  { name: "Russia", ar: "روسيا", code: "+7", iso: "ru", flag: "🇷🇺" },
  { name: "Rwanda", ar: "رواندا", code: "+250", iso: "rw", flag: "🇷🇼" },
  { name: "Saint Kitts and Nevis", ar: "سانت كيتس ونيفيس", code: "+1869", iso: "kn", flag: "🇰🇳" },
  { name: "Saint Lucia", ar: "سانت لوسيا", code: "+1758", iso: "lc", flag: "🇱🇨" },
  { name: "Saint Vincent and the Grenadines", ar: "سانت فنسنت وجزر غرينادين", code: "+1784", iso: "vc", flag: "🇻🇨" },
  { name: "Samoa", ar: "ساموا", code: "+685", iso: "ws", flag: "🇼🇸" },
  { name: "San Marino", ar: "سان مارينو", code: "+378", iso: "sm", flag: "🇸🇲" },
  { name: "Sao Tome and Principe", ar: "ساو تومي وبرينسيبي", code: "+239", iso: "st", flag: "🇸🇹" },
  { name: "Saudi Arabia", ar: "المملكة العربية السعودية", code: "+966", iso: "sa", flag: "🇸🇦" },
  { name: "Senegal", ar: "السنغال", code: "+221", iso: "sn", flag: "🇸🇳" },
  { name: "Serbia", ar: "صربيا", code: "+381", iso: "rs", flag: "🇷🇸" },
  { name: "Seychelles", ar: "سيشل", code: "+248", iso: "sc", flag: "🇸🇨" },
  { name: "Sierra Leone", ar: "سيراليون", code: "+232", iso: "sl", flag: "🇸🇱" },
  { name: "Singapore", ar: "سنغافورة", code: "+65", iso: "sg", flag: "🇸🇬" },
  { name: "Slovakia", ar: "سلوفاكيا", code: "+421", iso: "sk", flag: "🇸🇰" },
  { name: "Slovenia", ar: "سلوفينيا", code: "+386", iso: "si", flag: "🇸🇮" },
  { name: "Solomon Islands", ar: "جزر سليمان", code: "+677", iso: "sb", flag: "🇸🇧" },
  { name: "Somalia", ar: "الصومال", code: "+252", iso: "so", flag: "🇸🇴" },
  { name: "South Africa", ar: "جنوب أفريقيا", code: "+27", iso: "za", flag: "🇿🇦" },
  { name: "South Korea", ar: "كوريا الجنوبية", code: "+82", iso: "kr", flag: "🇰🇷" },
  { name: "South Sudan", ar: "جنوب السودان", code: "+211", iso: "ss", flag: "🇸🇸" },
  { name: "Spain", ar: "إسبانيا", code: "+34", iso: "es", flag: "🇪🇸" },
  { name: "Sri Lanka", ar: "سريلانكا", code: "+94", iso: "lk", flag: "🇱🇰" },
  { name: "Sudan", ar: "السودان", code: "+249", iso: "sd", flag: "🇸🇩" },
  { name: "Suriname", ar: "سورينام", code: "+597", iso: "sr", flag: "🇸🇷" },
  { name: "Sweden", ar: "السويد", code: "+46", iso: "se", flag: "🇸🇪" },
  { name: "Switzerland", ar: "سويسرا", code: "+41", iso: "ch", flag: "🇨🇭" },
  { name: "Syria", ar: "سوريا", code: "+963", iso: "sy", flag: "🇸🇾" },
  { name: "Tajikistan", ar: "طاجيكستان", code: "+992", iso: "tj", flag: "🇹🇯" },
  { name: "Tanzania", ar: "تنزانيا", code: "+255", iso: "tz", flag: "🇹🇿" },
  { name: "Thailand", ar: "تايلاند", code: "+66", iso: "th", flag: "🇹🇭" },
  { name: "Timor-Leste", ar: "تيمور - ليشتي", code: "+670", iso: "tl", flag: "🇹🇱" },
  { name: "Togo", ar: "توغو", code: "+228", iso: "tg", flag: "🇹🇬" },
  { name: "Tonga", ar: "تونغا", code: "+676", iso: "to", flag: "🇹🇴" },
  { name: "Trinidad and Tobago", ar: "ترينيداد وتوباغو", code: "+1868", iso: "tt", flag: "🇹🇹" },
  { name: "Tunisia", ar: "تونس", code: "+216", iso: "tn", flag: "🇹🇳" },
  { name: "Turkey", ar: "تركيا", code: "+90", iso: "tr", flag: "🇹🇷" },
  { name: "Turkmenistan", ar: "تركمانستان", code: "+993", iso: "tm", flag: "🇹🇲" },
  { name: "Tuvalu", ar: "توفالو", code: "+688", iso: "tv", flag: "🇹🇻" },
  { name: "Uganda", ar: "أوغندا", code: "+256", iso: "ug", flag: "🇺🇬" },
  { name: "Ukraine", ar: "أوكرانيا", code: "+380", iso: "ua", flag: "🇺🇦" },
  { name: "United Arab Emirates", ar: "الإمارات العربية المتحدة", code: "+971", iso: "ae", flag: "🇦🇪" },
  { name: "United Kingdom", ar: "المملكة المتحدة", code: "+44", iso: "gb", flag: "🇬🇧" },
  { name: "United States", ar: "الولايات المتحدة", code: "+1", iso: "us", flag: "🇺🇸" },
  { name: "Uruguay", ar: "أورغواي", code: "+598", iso: "uy", flag: "🇺🇾" },
  { name: "Uzbekistan", ar: "أوزبكستان", code: "+998", iso: "uz", flag: "🇺🇿" },
  { name: "Vanuatu", ar: "فانواتو", code: "+678", iso: "vu", flag: "🇻🇺" },
  { name: "Vatican City", ar: "الفاتيكان", code: "+379", iso: "va", flag: "🇻🇦" },
  { name: "Venezuela", ar: "فنزويلا", code: "+58", iso: "ve", flag: "🇻🇪" },
  { name: "Vietnam", ar: "فيتنام", code: "+84", iso: "vn", flag: "🇻🇳" },
  { name: "Yemen", ar: "اليمن", code: "+967", iso: "ye", flag: "🇾🇪" },
  { name: "Zambia", ar: "زامبيا", code: "+260", iso: "zm", flag: "🇿🇲" },
  { name: "Zimbabwe", ar: "زيمبابوي", code: "+263", iso: "zw", flag: "🇿🇼" },
];

export default countries;
